# Generated by Django 5.2.7 on 2025-11-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('packing', 'Packing'), ('shipping', 'Shipping'), ('evaluate', 'Evaluate'), ('canceled', 'Canceled')], default='packing', max_length=20),
        ),
    ]
