# Generated by Django 5.2.7 on 2025-11-06 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanceledOrderFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('change_address', 'Change shipping address'), ('change_size', 'Change size'), ('add_discount', 'Add discount code'), ('change_product', 'Change product'), ('no_need', 'No longer needed'), ('other', 'Other reason')], max_length=50)),
                ('other_description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canceled_feedback', to='orders.order')),
            ],
        ),
    ]
