# Generated by Django 5.2.7 on 2025-11-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_canceledorderfeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canceledorderfeedback",
            name="reason",
            field=models.CharField(
                choices=[
                    ("Change shipping address", "Change Address"),
                    ("Change size", "Change Size"),
                    ("Add discount code", "Add Discount"),
                    ("Change product", "Change Product"),
                    ("No longer needed", "No Need"),
                    ("Other reason", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
