# Generated by Django 5.2.7 on 2025-11-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=20),
        ),
    ]
